// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY0024Bkfx8zFbHvrIoafX560e0xT_85I',
    appId: '1:293621515317:web:ba61125d113425ee3e9d7c',
    messagingSenderId: '293621515317',
    projectId: 'untitled-f448a',
    authDomain: 'untitled-f448a.firebaseapp.com',
    storageBucket: 'untitled-f448a.appspot.com',
    measurementId: 'G-BHYTRKJQSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrtU9mp2cKCUFT9VGUhKFMwqLeeaVWJyQ',
    appId: '1:293621515317:android:cbec0f8fe79216ba3e9d7c',
    messagingSenderId: '293621515317',
    projectId: 'untitled-f448a',
    storageBucket: 'untitled-f448a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdYMLusA7x2utfzDM28XvOtCrHSSpXJas',
    appId: '1:293621515317:ios:8a972a8bf78057f83e9d7c',
    messagingSenderId: '293621515317',
    projectId: 'untitled-f448a',
    storageBucket: 'untitled-f448a.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdYMLusA7x2utfzDM28XvOtCrHSSpXJas',
    appId: '1:293621515317:ios:8a972a8bf78057f83e9d7c',
    messagingSenderId: '293621515317',
    projectId: 'untitled-f448a',
    storageBucket: 'untitled-f448a.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY0024Bkfx8zFbHvrIoafX560e0xT_85I',
    appId: '1:293621515317:web:a4e2be1499b5188a3e9d7c',
    messagingSenderId: '293621515317',
    projectId: 'untitled-f448a',
    authDomain: 'untitled-f448a.firebaseapp.com',
    storageBucket: 'untitled-f448a.appspot.com',
    measurementId: 'G-689D3YR7SH',
  );
}
